repos:
    -   repo: https://github.com/astral-sh/uv-pre-commit
        rev: 0.4.29 # uv version
        hooks:
        # Compile requirements
          - id: pip-compile
            args: [requirements.in, -o, requirements.txt]


    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: check-yaml
        -   id: sort-simple-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace


    -   repo: https://github.com/astral-sh/ruff-pre-commit
        # Ruff version.
        rev: v0.7.2
        hooks:
        # Run the linter and fix.
        -   id: ruff
            args: [--fix]
        # Run the formatter.
        -   id: ruff-format


    -   repo: https://github.com/gitleaks/gitleaks
        rev: v8.15.0 # Use the latest version available
        hooks:
            -   id: gitleaks
                args: ["protect", "--staged"]
