name: Code Quality Checks
# https://docs.astral.sh/uv/guides/integration/github/

on:
    push:
        branches:
            -   main
    pull_request:
        branches:
            -   main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v4

        -   name: Install uv
            uses: astral-sh/setup-uv@v3

        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version-file: ".python-version"

        -   name: Install the project
            run: uv sync --all-extras --dev

        -   name: Install Code Quality Libraries
            run: uv pip install pytest pytest-cov flake8

        -   name: Run pytest coverage and flake8 linter
            run: flake8 --statistics
