name: Code Quality Checks
# https://docs.astral.sh/uv/guides/integration/github/

on:
    push:
        branches:
            -   main
    pull_request:
        branches:
            -   main

jobs:
    pre-commit-hook:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v4

        -   name: Install uv
            uses: astral-sh/setup-uv@v3

        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version-file: ".python-version"

        -   name: Install the project
            run: uv sync --all-extras --dev

        -   name: Install pre-commit
            run: uv pip install pre-commit

        -   name: Run pre-commit-hook
            run: uv run pre-commit run --all-files

    mypy:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v4

        -   name: Install uv
            uses: astral-sh/setup-uv@v3

        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version-file: ".python-version"

        -   name: Install the project
            run: uv sync --all-extras --dev

        -   name: Install mypy
            run: uv pip install mypy

        -   name: Run MyPy
            run: uv run -m mypy src/pdm_companion --check-untyped-defs --ignore-missing-imports

        -   name: Upload Quality Results
            if: always()
            uses: actions/upload-artifact@v4
            with:
                name: mypy-results
                path: artifacts
