name: Run Tests Using UV Package Manager
# https://docs.astral.sh/uv/guides/integration/github/

on:
    push:
        branches:
            -   main
    pull_request:
        branches:
            -   main

jobs:
    backend-tests:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v4

        -   name: Install uv
            uses: astral-sh/setup-uv@v3

        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version-file: ".python-version"

        -   name: Install the project
            run: uv sync --all-extras --dev

        -   name: Install pytest
            run: uv pip install pytest

        -   name: Create results directory in root
            run: mkdir -p $GITHUB_WORKSPACE/pytest_results

        -   name: Run tests
            env:
                OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY  }}
            run: uv run pytest tests --junitxml=$GITHUB_WORKSPACE/pytest_results/pytest_report.xml
            continue-on-error: true

    upload-test-results:
        needs: backend-tests
        runs-on: ubuntu-latest
        steps:
        -   name: Upload Test Results
            if: always()
            uses: actions/upload-artifact@v4
            with:
                name: pytest-results
                path: $GITHUB_WORKSPACE/pytest_results/
