name: Tests
# https://docs.astral.sh/uv/guides/integration/github/

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run tests
      # For example, using `pytest`
      run: uv run pytest tests

